dev:
	pnpm dev

ci: setup lint test build

format: setup
	pnpm format

lint: setup
	pnpm lint

test: setup
	pnpm test

setup:
	pnpm install

build: setup
	pnpm build

release: build

clean:
	pnpm clean
